import { library } from '@fortawesome/fontawesome-svg-core';
import { fas } from '@fortawesome/free-solid-svg-icons';
import './styles/index.scss';
library.add(fas);

export { default as AutoComplete } from './components/AutoComplete';
export { default as Avatar } from './components/Avatar';
export { default as Button } from './components/Button';
export { default as Flex } from './components/Flex';
export { default as Form } from './components/Form';
export { default as Grid } from './components/Grid';
export { default as Icon } from './components/Icon';
export { default as Input } from './components/Input';
export { default as Menu } from './components/Menu';
export { default as Progress } from './components/Progress';
export { default as Space } from './components/Space';
export { default as Switch } from './components/Switch';
export { default as Tab } from './components/Tab';
export { default as Transition } from './components/Transition';
export { default as Upload } from './components/Upload';
