name: Vitest CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Cache pnpm store
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    
    - name: Install dependencies
      run: pnpm install

    - name: Run Vitest with Coverage
      run: pnpm run test:coverage

    - name: 'Report Coverage'
      if: always()
      uses: davelosert/vitest-coverage-report-action@v2
      with:
        json-final-path: './coverage/coverage-final.json'
        json-summary-path: './coverage/coverage-summary.json'
        github-token: ${{ secrets.GITHUB_TOKEN }}